export const divisions = [
  "Dhaka",
  "Chattogram",
  "Rajshahi",
  "Khulna",
  "Sylhet",
  "Barishal",
  "Rangpur",
  "Mymensingh",
];

export const districtsByDivision = {
  Dhaka: [
    "Dhaka",
    "Gazipur",
    "Narayanganj",
    "Narsingdi",
    "Tangail",
    "Manikganj",
    "Munshiganj",
    "Faridpur",
    "Gopalganj",
    "Madaripur",
    "Rajbari",
    "Shariatpur",
    "Kishoreganj",
  ],

  Chattogram: [
    "Chattogram",
    "Cox's Bazar",
    "Comilla",
    "Feni",
    "Noakhali",
    "Chandpur",
    "Brahmanbaria",
    "Lakshmipur",
    "Rangamati",
    "Bandarban",
    "Khagrachari",
  ],

  Rajshahi: [
    "Rajshahi",
    "Bogra",
    "Pabna",
    "Natore",
    "Naogaon",
    "Joypurhat",
    "Sirajganj",
    "Chapainawabganj",
  ],

  Khulna: [
    "Khulna",
    "Jessore",
    "Satkhira",
    "Kushtia",
    "Meherpur",
    "Jhenaidah",
    "Magura",
    "Narail",
    "Bagerhat",
    "Chuadanga",
  ],

  Sylhet: ["Sylhet", "Moulvibazar", "Habiganj", "Sunamganj"],

  Barishal: [
    "Barishal",
    "Bhola",
    "Patuakhali",
    "Pirojpur",
    "Jhalokathi",
    "Barguna",
  ],

  Rangpur: [
    "Rangpur",
    "Dinajpur",
    "Kurigram",
    "Nilphamari",
    "Lalmonirhat",
    "Gaibandha",
    "Panchagarh",
    "Thakurgaon",
  ],

  Mymensingh: ["Mymensingh", "Jamalpur", "Netrokona", "Sherpur"],
};

export const citiesByDistrict = {
  Dhaka: ["Dhaka", "Savar", "Keraniganj", "Uttara"],
  Gazipur: ["Gazipur", "Tongi", "Kaliakair"],
  Narayanganj: ["Narayanganj", "Sonargaon", "Rupganj"],
  Narsingdi: ["Narsingdi", "Palash", "Raipura"],
  Tangail: ["Tangail", "Mirzapur"],
  Manikganj: ["Manikganj", "Singair"],
  Munshiganj: ["Munshiganj", "Sreenagar"],
  Faridpur: ["Faridpur", "Boalmari"],
  Gopalganj: ["Gopalganj", "Tungipara"],
  Madaripur: ["Madaripur", "Rajoir"],
  Rajbari: ["Rajbari", "Pangsha"],
  Shariatpur: ["Shariatpur", "Damudya"],
  Kishoreganj: ["Kishoreganj", "Bhairab"],

  Chattogram: ["Chattogram", "Sitakunda", "Patiya"],
  "Cox's Bazar": ["Cox's Bazar", "Teknaf", "Ukhia"],
  Comilla: ["Comilla", "Daudkandi"],
  Feni: ["Feni", "Daganbhuiyan"],
  Noakhali: ["Noakhali", "Maijdee"],
  Chandpur: ["Chandpur", "Haimchar"],
  Brahmanbaria: ["Brahmanbaria", "Ashuganj"],
  Lakshmipur: ["Lakshmipur", "Raipur"],
  Rangamati: ["Rangamati"],
  Bandarban: ["Bandarban"],
  Khagrachari: ["Khagrachari"],

  Rajshahi: ["Rajshahi", "Puthia"],
  Bogra: ["Bogra", "Shibganj"],
  Pabna: ["Pabna", "Ishwardi"],
  Natore: ["Natore", "Singra"],
  Naogaon: ["Naogaon", "Patnitala"],
  Joypurhat: ["Joypurhat"],
  Sirajganj: ["Sirajganj", "Kazipur"],
  Chapainawabganj: ["Chapainawabganj"],

  Khulna: ["Khulna", "Dumuria"],
  Jessore: ["Jessore", "Jhikargacha"],
  Satkhira: ["Satkhira", "Kaliganj"],
  Kushtia: ["Kushtia", "Bheramara"],
  Meherpur: ["Meherpur"],
  Jhenaidah: ["Jhenaidah"],
  Magura: ["Magura"],
  Narail: ["Narail"],
  Bagerhat: ["Bagerhat", "Mongla"],
  Chuadanga: ["Chuadanga"],

  Sylhet: ["Sylhet", "Beanibazar"],
  Moulvibazar: ["Moulvibazar", "Srimangal"],
  Habiganj: ["Habiganj"],
  Sunamganj: ["Sunamganj"],

  Barishal: ["Barishal", "Bakerganj"],
  Bhola: ["Bhola", "Char Fasson"],
  Patuakhali: ["Patuakhali"],
  Pirojpur: ["Pirojpur"],
  Jhalokathi: ["Jhalokathi"],
  Barguna: ["Barguna"],

  Rangpur: ["Rangpur", "Badarganj"],
  Dinajpur: ["Dinajpur", "Parbatipur"],
  Kurigram: ["Kurigram"],
  Nilphamari: ["Nilphamari"],
  Lalmonirhat: ["Lalmonirhat"],
  Gaibandha: ["Gaibandha"],
  Panchagarh: ["Panchagarh"],
  Thakurgaon: ["Thakurgaon"],

  Mymensingh: ["Mymensingh", "Trishal"],
  Jamalpur: ["Jamalpur"],
  Netrokona: ["Netrokona"],
  Sherpur: ["Sherpur"],
};

export const areasByCity = {
  Dhaka: [
    "Gulshan",
    "Banani",
    "Dhanmondi",
    "Uttara",
    "Mirpur",
    "Mohammadpur",
    "Motijheel",
    "Badda",
    "Tejgaon",
    "Bashundhara",
  ],

  Uttara: [
    "Sector 1",
    "Sector 3",
    "Sector 6",
    "Sector 7",
    "Sector 10",
    "Sector 11",
    "Sector 12",
    "Sector 13",
  ],

  Chattogram: ["Agrabad", "GEC Circle", "Khulshi", "Panchlaish", "Halishahar"],

  Sylhet: ["Zindabazar", "Amberkhana", "Uposhohor", "Tilagor"],

  Khulna: ["Sonadanga", "Boyra", "Khalishpur", "Daulatpur"],

  Rajshahi: ["Shaheb Bazar", "Upashahar", "Padma Residential"],
};
